sudo: required
language: go
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.7.1
  matrix:
    secure: C4RSLXbqJ4i0TPzMXEMUs6u6YHY1iiL54YpJfGqs4Ce0VXJ17GP9s6WPWqo2hdmDs4FfoAm6Kdaa/1FYZBU95IzbVmTfABhynnnthet83eyjLRlnjXsgxgaSAYtBUp8gM4cjAkkWTXYrrj6a9zaO8apz4dufXnncrD/p39Xu/LSdik1KBEoNXktbLT90jRpza5HQjzQ0A4DjF4b5Mn9om2X5VIFurbFa86cIzQj9QRcrl9Ch1qhgY09H5Z0gtGKdDBUE7bzVxYqy3i7jfq1sR22SmqXySqgGlPQNOMGU0inr3rJkZtcaR3CFLofHtLwFpYQK1egqXA/rm7naEyrvAi9ZaTz5PCExubkgzj6JcUG07qLT6IzXAUIqBMS068RgpgflphEADf7k5VdgZ5Udez0OqTGhpUZCWaRQV5jpC/4yk4LrV1k4yOQSNBdSccVAj5JVZumjFCUMGb0qefxzysMq0a0kX19Qv0OIY93OgTKUBCrWp4oWZZiM35o/Yn+Y4JzIJMJHpt67Y0NZ27W5x45oF04Ewv2H2ztvc2DUBlAzwccUKo7Dc4WJQcT0Mrg+UZiApxBauXdSuDuELoHIqF0Vn9tHf9p1LEfwF81BCbigW6rbpC1X0kzEG0f/B9CdSoGqH6nnmXIBHUdgoB2oQLI6Rpik7OKXXBGJtRKCT2Q=
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- docker-compose run dev make
after_success:
- sudo chown --changes --recursive $(whoami):$(id --group $(whoami)) .
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker build -t geodata/ogo-ical:latest .
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push geodata/ogo-ical:latest;
  fi
