sudo: required
language: go
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.7.1
  matrix:
    secure: C4RSLXbqJ4i0TPzMXEMUs6u6YHY1iiL54YpJfGqs4Ce0VXJ17GP9s6WPWqo2hdmDs4FfoAm6Kdaa/1FYZBU95IzbVmTfABhynnnthet83eyjLRlnjXsgxgaSAYtBUp8gM4cjAkkWTXYrrj6a9zaO8apz4dufXnncrD/p39Xu/LSdik1KBEoNXktbLT90jRpza5HQjzQ0A4DjF4b5Mn9om2X5VIFurbFa86cIzQj9QRcrl9Ch1qhgY09H5Z0gtGKdDBUE7bzVxYqy3i7jfq1sR22SmqXySqgGlPQNOMGU0inr3rJkZtcaR3CFLofHtLwFpYQK1egqXA/rm7naEyrvAi9ZaTz5PCExubkgzj6JcUG07qLT6IzXAUIqBMS068RgpgflphEADf7k5VdgZ5Udez0OqTGhpUZCWaRQV5jpC/4yk4LrV1k4yOQSNBdSccVAj5JVZumjFCUMGb0qefxzysMq0a0kX19Qv0OIY93OgTKUBCrWp4oWZZiM35o/Yn+Y4JzIJMJHpt67Y0NZ27W5x45oF04Ewv2H2ztvc2DUBlAzwccUKo7Dc4WJQcT0Mrg+UZiApxBauXdSuDuELoHIqF0Vn9tHf9p1LEfwF81BCbigW6rbpC1X0kzEG0f/B9CdSoGqH6nnmXIBHUdgoB2oQLI6Rpik7OKXXBGJtRKCT2Q=
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -i -L http://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin/docker-compose
- cat /usr/local/bin/docker-compose
- echo "http://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname-s`-`uname -m`"
script:
- ls -lh /usr/local/bin/docker-compose
- /usr/local/bin/docker-compose help
- /usr/local/bin/docker-compose run dev true
- /usr/local/bin/docker-compose run dev make
after_success:
- sudo chown --changes --recursive $(whoami):$(id --group $(whoami)) .
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker build -t geodata/ogo-ical:latest .;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push geodata/ogo-ical:latest;
  fi
deploy:
  provider: releases
  api_key:
    secure: kBugvzSSGedyNaftDQCSL7HsED6TZTUME8Wk2/RysNSGMsPXs6QkYoQ7xgGPrNqKTlO0orf9BaytSf8QXhnq0UkwKEQwoj68wbx1kspW08BjBF/aW56LhixDk8mFL12Ew5E+lwVJ6sln0IR8QquHHwDXNnEkEtHsWJjO4St/+7faZTe/Ud1KTY6MHDKfAAxbTAbm2YMv0V2mwx4QZQ8cZOKSzBE82uHeLnle0ua6zvrb8iEF40G800Hu2njcc5T3tDMD2F1OnqkskLDASQfMGElp7J3l96Aq4kkW148yxEKuyTQ16IaSnOjdYZUALuYxyZsurSCibf/UQSumvifAbQzMmykehFSSh759+eof3pIutm53iLu49wM6PYVD0UKEBOhsSCE0ZWfmEmr/7Sv6/DbmSG1UD1Nw//2p29WqgppiunNdyp+fC8fc+MiStkXmxT4/ZeMszo0nXrO72nw1c808hAuZdUyCriezqbs5vtBtRvG6cfL2SQPeNxuZaUd+B+/2puKxAZdzsmGf/HBFaLF17J743q2Y7J7g6bf9wfjo3gjsrosb89IEqccRP8Pubi24PCQD+P7Kt0eHXSgK6W+DNfTn3wSP0O/ktgMbIBgG8iir+0Tcu6A2/ifLK7xgnXyK8NqMeH8n+b4V5ynFkwTX8mh0CON1734ffz9Vcqk=
  file: ogo-ical
  skip_cleanup: true
  on:
    repo: geo-data/ogo-ical
